name: my_web_project
description: A new Flutter web project.
publish_to: 'none' # ไม่ต้อง publish ไปที่ pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # เพิ่ม dependencies อื่น ๆ ที่คุณต้องการได้ที่นี่

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icon.png
    - assets/google.png
